/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { User } from './user';

/**
* Details about a project component.
*/
export class Component {
    /**
    * The URL of the component.
    */
    'self'?: string;
    /**
    * The unique identifier for the component.
    */
    'id'?: string;
    /**
    * The unique name for the component in the project. Required when creating a component. Optional when updating a component. The maximum length is 255 characters.
    */
    'name'?: string;
    /**
    * The description for the component. Optional when creating or updating a component.
    */
    'description'?: string;
    /**
    * The user details for the component's lead user.
    */
    'lead'?: User;
    /**
    * This property has been deprecated in favour of `leadAccountId` due to privacy changes. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.   The username of the component's lead user. Optional when creating or updating a component. Cannot be provided with `leadAccountId`.
    */
    'leadUserName'?: string;
    /**
    * The accountId of the component's lead user. The accountId uniquely identifies the user across all Atlassian products. For example, _384093:32b4d9w0-f6a5-3535-11a3-9c8c88d10192_.Optional when creating or updating a component. Cannot be provided with `leadUserName`.
    */
    'leadAccountId'?: string;
    /**
    * The nominal user type used to determine the assignee for issues created with this component. See `realAssigneeType` for details on how the type of the user, and hence the user, assigned to issues is determined. Can take the following values:  *   `PROJECT_LEAD` the assignee to any issues created with this component is nominally the lead for the project the component is in. *   `COMPONENT_LEAD` the assignee to any issues created with this component is nominally the lead for the component. *   `UNASSIGNED` an assignee is not set for issues created with this component. *   `PROJECT_DEFAULT` the assignee to any issues created with this component is nominally the default assignee for the project that the component is in.  Default value: `PROJECT_DEFAULT`.   Optional when creating or updating a component.
    */
    'assigneeType'?: Component.AssigneeTypeEnum;
    /**
    * The details of the user associated with `assigneeType`, if any. See `realAssignee` for details of the user assigned to issues created with this component.
    */
    'assignee'?: User;
    /**
    * The actual type of the assignee that is assigned to issues created with this component, when an assignee cannot be set from the `assigneeType`. For example, `assigneeType` is set to `COMPONENT_LEAD` but no component lead is set. This property is set to one of the following values:  *   `PROJECT_LEAD` when `assigneeType` is `PROJECT_LEAD` and the project lead has permission to be assigned issues in the project that the component is in. *   `COMPONENT_LEAD` when `assignee`Type is `COMPONENT_LEAD` and the component lead has permission to be assigned issues in the project that the component is in. *   `UNASSIGNED` when `assigneeType` is `UNASSIGNED` and Jira is configured to allow unassigned issues. *   `PROJECT_DEFAULT` when none of the preceding cases are true.
    */
    'realAssigneeType'?: Component.RealAssigneeTypeEnum;
    /**
    * The user assigned to issues created with this component, when `assigneeType` does not identify a valid assignee.
    */
    'realAssignee'?: User;
    /**
    * Whether or not a user is associated with `assigneeType`. For example, if the `assigneeType` is set to `COMPONENT_LEAD` but the component lead is not set, then `false` is returned.
    */
    'isAssigneeTypeValid'?: boolean;
    /**
    * The key of the project to which the component is assigned. Required when creating a component. Can't be updated.
    */
    'project'?: string;
    /**
    * Not used.
    */
    'projectId'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "self",
            "baseName": "self",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "lead",
            "baseName": "lead",
            "type": "User"
        },
        {
            "name": "leadUserName",
            "baseName": "leadUserName",
            "type": "string"
        },
        {
            "name": "leadAccountId",
            "baseName": "leadAccountId",
            "type": "string"
        },
        {
            "name": "assigneeType",
            "baseName": "assigneeType",
            "type": "Component.AssigneeTypeEnum"
        },
        {
            "name": "assignee",
            "baseName": "assignee",
            "type": "User"
        },
        {
            "name": "realAssigneeType",
            "baseName": "realAssigneeType",
            "type": "Component.RealAssigneeTypeEnum"
        },
        {
            "name": "realAssignee",
            "baseName": "realAssignee",
            "type": "User"
        },
        {
            "name": "isAssigneeTypeValid",
            "baseName": "isAssigneeTypeValid",
            "type": "boolean"
        },
        {
            "name": "project",
            "baseName": "project",
            "type": "string"
        },
        {
            "name": "projectId",
            "baseName": "projectId",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Component.attributeTypeMap;
    }
}

export namespace Component {
    export enum AssigneeTypeEnum {
        PROJECTDEFAULT = <any> 'PROJECT_DEFAULT',
        COMPONENTLEAD = <any> 'COMPONENT_LEAD',
        PROJECTLEAD = <any> 'PROJECT_LEAD',
        UNASSIGNED = <any> 'UNASSIGNED'
    }
    export enum RealAssigneeTypeEnum {
        PROJECTDEFAULT = <any> 'PROJECT_DEFAULT',
        COMPONENTLEAD = <any> 'COMPONENT_LEAD',
        PROJECTLEAD = <any> 'PROJECT_LEAD',
        UNASSIGNED = <any> 'UNASSIGNED'
    }
}
