/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TimeTrackingConfiguration } from './timeTrackingConfiguration';

/**
* Details about the configuration of Jira.
*/
export class Configuration {
    /**
    * Whether the ability for users to vote on issues is enabled. See [Configuring Jira application options](https://confluence.atlassian.com/x/uYXKM) for details.
    */
    'votingEnabled'?: boolean;
    /**
    * Whether the ability for users to watch issues is enabled. See [Configuring Jira application options](https://confluence.atlassian.com/x/uYXKM) for details.
    */
    'watchingEnabled'?: boolean;
    /**
    * Whether the ability to create unassigned issues is enabled. See [Configuring Jira application options](https://confluence.atlassian.com/x/uYXKM) for details.
    */
    'unassignedIssuesAllowed'?: boolean;
    /**
    * Whether the ability to create sub-tasks for issues is enabled.
    */
    'subTasksEnabled'?: boolean;
    /**
    * Whether the ability to link issues is enabled.
    */
    'issueLinkingEnabled'?: boolean;
    /**
    * Whether the ability to track time is enabled.
    */
    'timeTrackingEnabled'?: boolean;
    /**
    * Whether the ability to add attachments to issues is enabled.
    */
    'attachmentsEnabled'?: boolean;
    /**
    * The configuration of time tracking.
    */
    'timeTrackingConfiguration'?: TimeTrackingConfiguration;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "votingEnabled",
            "baseName": "votingEnabled",
            "type": "boolean"
        },
        {
            "name": "watchingEnabled",
            "baseName": "watchingEnabled",
            "type": "boolean"
        },
        {
            "name": "unassignedIssuesAllowed",
            "baseName": "unassignedIssuesAllowed",
            "type": "boolean"
        },
        {
            "name": "subTasksEnabled",
            "baseName": "subTasksEnabled",
            "type": "boolean"
        },
        {
            "name": "issueLinkingEnabled",
            "baseName": "issueLinkingEnabled",
            "type": "boolean"
        },
        {
            "name": "timeTrackingEnabled",
            "baseName": "timeTrackingEnabled",
            "type": "boolean"
        },
        {
            "name": "attachmentsEnabled",
            "baseName": "attachmentsEnabled",
            "type": "boolean"
        },
        {
            "name": "timeTrackingConfiguration",
            "baseName": "timeTrackingConfiguration",
            "type": "TimeTrackingConfiguration"
        }    ];

    static getAttributeTypeMap() {
        return Configuration.attributeTypeMap;
    }
}

