/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* The converted JQL queries.
*/
export class ConvertedJQLQueries {
    /**
    * The list of converted query strings with account IDs in place of user identifiers.
    */
    'queryStrings'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "queryStrings",
            "baseName": "queryStrings",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ConvertedJQLQueries.attributeTypeMap;
    }
}

