/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IssueType } from './issueType';
import { Priority } from './priority';
import { StatusDetails } from './statusDetails';
import { UserDetails } from './userDetails';

/**
* Key fields from the linked issue.
*/
export class Fields {
    /**
    * The summary description of the linked issue.
    */
    'summary'?: string;
    /**
    * The status of the linked issue.
    */
    'status'?: StatusDetails;
    /**
    * The type of the linked issue.
    */
    'issuetype'?: IssueType;
    /**
    * The priority of the linked issue.
    */
    'priority'?: Priority;
    /**
    * The assignee of the linked issue.
    */
    'assignee'?: UserDetails;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "StatusDetails"
        },
        {
            "name": "issuetype",
            "baseName": "issuetype",
            "type": "IssueType"
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "Priority"
        },
        {
            "name": "assignee",
            "baseName": "assignee",
            "type": "UserDetails"
        }    ];

    static getAttributeTypeMap() {
        return Fields.attributeTypeMap;
    }
}

