/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HistoryMetadataParticipant } from './historyMetadataParticipant';

/**
* Details of issue history metadata.
*/
export class HistoryMetadata {
    /**
    * The type of the history record.
    */
    'type'?: string;
    /**
    * The description of the history record.
    */
    'description'?: string;
    /**
    * The activity described in the history record.
    */
    'activityDescription'?: string;
    /**
    * This property is deprecated.
    */
    'activityDescriptionKey'?: string;
    /**
    * The description of the email address associated the history record.
    */
    'emailDescription'?: string;
    /**
    * This property is deprecated.
    */
    'emailDescriptionKey'?: string;
    /**
    * Details of the user whose action created the history record.
    */
    'actor'?: HistoryMetadataParticipant;
    /**
    * Details of the system that generated the history record.
    */
    'generator'?: HistoryMetadataParticipant;
    /**
    * Details of the cause that triggered the creation the history record.
    */
    'cause'?: HistoryMetadataParticipant;
    /**
    * Additional arbitrary information about the history record.
    */
    'extraData'?: { [key: string]: string; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "activityDescription",
            "baseName": "activityDescription",
            "type": "string"
        },
        {
            "name": "activityDescriptionKey",
            "baseName": "activityDescriptionKey",
            "type": "string"
        },
        {
            "name": "emailDescription",
            "baseName": "emailDescription",
            "type": "string"
        },
        {
            "name": "emailDescriptionKey",
            "baseName": "emailDescriptionKey",
            "type": "string"
        },
        {
            "name": "actor",
            "baseName": "actor",
            "type": "HistoryMetadataParticipant"
        },
        {
            "name": "generator",
            "baseName": "generator",
            "type": "HistoryMetadataParticipant"
        },
        {
            "name": "cause",
            "baseName": "cause",
            "type": "HistoryMetadataParticipant"
        },
        {
            "name": "extraData",
            "baseName": "extraData",
            "type": "{ [key: string]: string; }"
        }    ];

    static getAttributeTypeMap() {
        return HistoryMetadata.attributeTypeMap;
    }
}

