/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* An icon.
*/
export class Icon {
    /**
    * The URL of a 16x16 pixel icon.
    */
    'url16x16'?: string;
    /**
    * The title of the icon, for use as a tooltip on the icon.
    */
    'title'?: string;
    /**
    * The URL of the tooltip, used only for a status icon.
    */
    'link'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "url16x16",
            "baseName": "url16x16",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Icon.attributeTypeMap;
    }
}

