/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Bulk operation filter details.
*/
export class IssueFilterForBulkPropertySet {
    /**
    * List of issues to perform the bulk operation on.
    */
    'entityIds'?: Array<number>;
    /**
    * The value of properties to perform the bulk operation on.
    */
    'currentValue'?: any;
    /**
    * Indicates whether the bulk operation occurs only when the property is present on or absent from an issue.
    */
    'hasProperty'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "entityIds",
            "baseName": "entityIds",
            "type": "Array<number>"
        },
        {
            "name": "currentValue",
            "baseName": "currentValue",
            "type": "any"
        },
        {
            "name": "hasProperty",
            "baseName": "hasProperty",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return IssueFilterForBulkPropertySet.attributeTypeMap;
    }
}

