/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IssueFieldOptionConfiguration } from './issueFieldOptionConfiguration';

export class IssueFieldOptionCreateBean {
    /**
    * The option's name, which is displayed in the UI.
    */
    'value': string;
    /**
    * The properties can be any arbitrary key value pairs. These properties can be searched using JQL, if the extractions (see https://developer.atlassian.com/cloud/jira/platform/modules/issue-field-option-property-index/) are defined in the descriptor for the issue field module.
    */
    'properties'?: { [key: string]: any; };
    'config'?: IssueFieldOptionConfiguration;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "config",
            "baseName": "config",
            "type": "IssueFieldOptionConfiguration"
        }    ];

    static getAttributeTypeMap() {
        return IssueFieldOptionCreateBean.attributeTypeMap;
    }
}

