/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JiraExpressionContext } from './jiraExpressionContext';

export class JiraExpressionEvalRequestBean {
    /**
    * The Jira expression to evaluate.
    */
    'expression': string;
    'context'?: JiraExpressionContext;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "expression",
            "baseName": "expression",
            "type": "string"
        },
        {
            "name": "context",
            "baseName": "context",
            "type": "JiraExpressionContext"
        }    ];

    static getAttributeTypeMap() {
        return JiraExpressionEvalRequestBean.attributeTypeMap;
    }
}

