/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JiraExpressionsComplexityBean } from './jiraExpressionsComplexityBean';

export class JiraExpressionEvaluationMetaDataBean {
    /**
    * Contains information about the expression complexity. For example, the number of steps it took to evaluate the expression.
    */
    'complexity'?: JiraExpressionsComplexityBean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "complexity",
            "baseName": "complexity",
            "type": "JiraExpressionsComplexityBean"
        }    ];

    static getAttributeTypeMap() {
        return JiraExpressionEvaluationMetaDataBean.attributeTypeMap;
    }
}

