/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ItemIdOrKey } from './itemIdOrKey';

/**
* Values for the variables used when evaluating the expression.
*/
export class JiraExpressionContext {
    'issue'?: ItemIdOrKey;
    'project'?: ItemIdOrKey;
    /**
    * The ID of the sprint that is available under the `sprint` variable when evaluating the expression.
    */
    'sprint'?: number;
    /**
    * The ID of the board that is available under the `board` variable when evaluating the expression.
    */
    'board'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "issue",
            "baseName": "issue",
            "type": "ItemIdOrKey"
        },
        {
            "name": "project",
            "baseName": "project",
            "type": "ItemIdOrKey"
        },
        {
            "name": "sprint",
            "baseName": "sprint",
            "type": "number"
        },
        {
            "name": "board",
            "baseName": "board",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return JiraExpressionContext.attributeTypeMap;
    }
}

