/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ErrorCollection } from './errorCollection';

export class NestedResponse {
    'status'?: number;
    'errorCollection'?: ErrorCollection;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "number"
        },
        {
            "name": "errorCollection",
            "baseName": "errorCollection",
            "type": "ErrorCollection"
        }    ];

    static getAttributeTypeMap() {
        return NestedResponse.attributeTypeMap;
    }
}

