/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GroupName } from './groupName';
import { UserDetails } from './userDetails';

/**
* Details of the users and groups to receive the notification.
*/
export class NotificationRecipients {
    /**
    * Indicates whether the notification should be sent to the issue's reporter.
    */
    'reporter'?: boolean;
    /**
    * Indicates whether the notification should be sent to the issue's assignees.
    */
    'assignee'?: boolean;
    /**
    * Indicates whether the notification should be sent to the issue's watchers.
    */
    'watchers'?: boolean;
    /**
    * Indicates whether the notification should be sent to the issue's voters.
    */
    'voters'?: boolean;
    /**
    * List of users to receive the notification.
    */
    'users'?: Array<UserDetails>;
    /**
    * List of groups to receive the notification.
    */
    'groups'?: Array<GroupName>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "reporter",
            "baseName": "reporter",
            "type": "boolean"
        },
        {
            "name": "assignee",
            "baseName": "assignee",
            "type": "boolean"
        },
        {
            "name": "watchers",
            "baseName": "watchers",
            "type": "boolean"
        },
        {
            "name": "voters",
            "baseName": "voters",
            "type": "boolean"
        },
        {
            "name": "users",
            "baseName": "users",
            "type": "Array<UserDetails>"
        },
        {
            "name": "groups",
            "baseName": "groups",
            "type": "Array<GroupName>"
        }    ];

    static getAttributeTypeMap() {
        return NotificationRecipients.attributeTypeMap;
    }
}

