/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Details about a notification event.
*/
export class NotificationEvent {
    /**
    * The ID of the event. The event can be [Jira system events](https://confluence.atlassian.com/x/8YdKLg#Creatinganotificationscheme-eventsEvents) [custom events](https://confluence.atlassian.com/x/AIlKLg).
    */
    'id'?: number;
    /**
    * The name of the event.
    */
    'name'?: string;
    /**
    * The description of the event.
    */
    'description'?: string;
    /**
    * The template of the event. Only custom events configured by Jira administrators have template.
    */
    'templateEvent'?: NotificationEvent;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "templateEvent",
            "baseName": "templateEvent",
            "type": "NotificationEvent"
        }    ];

    static getAttributeTypeMap() {
        return NotificationEvent.attributeTypeMap;
    }
}

