/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Field } from './field';
import { GroupName } from './groupName';
import { ProjectRole } from './projectRole';
import { UserDetails } from './userDetails';

/**
* Details of a user, group, field, or project role that holds a permission.For more information, see _Holder_ in [Get all permission schemes](#api-api-3-permissionscheme-get).
*/
export class PermissionHolder {
    /**
    * The type of permission holder.
    */
    'type': string;
    /**
    * The identifier of permission holder.
    */
    'parameter': string;
    /**
    * The user holding the permission.
    */
    'user'?: UserDetails;
    /**
    * The group holding the permission.
    */
    'group'?: GroupName;
    /**
    * The field holding the permission.
    */
    'field'?: Field;
    /**
    * The project role holding the permission.
    */
    'projectRole'?: ProjectRole;
    /**
    * Expand options that include additional permission holder details in the response.
    */
    'expand'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "parameter",
            "baseName": "parameter",
            "type": "string"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "UserDetails"
        },
        {
            "name": "group",
            "baseName": "group",
            "type": "GroupName"
        },
        {
            "name": "field",
            "baseName": "field",
            "type": "Field"
        },
        {
            "name": "projectRole",
            "baseName": "projectRole",
            "type": "ProjectRole"
        },
        {
            "name": "expand",
            "baseName": "expand",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PermissionHolder.attributeTypeMap;
    }
}

