/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AvatarUrls } from './avatarUrls';
import { IssueTypeIssueCreateMetadata } from './issueTypeIssueCreateMetadata';

/**
* Details of the issue creation metadata for a project.
*/
export class ProjectIssueCreateMetadata {
    /**
    * Expand options that include additional project issue create metadata details in the response.
    */
    'expand'?: string;
    /**
    * The URL of the project.
    */
    'self'?: string;
    /**
    * The ID of the project.
    */
    'id'?: string;
    /**
    * The key of the project.
    */
    'key'?: string;
    /**
    * The name of the project.
    */
    'name'?: string;
    /**
    * List of the project's avatars, returning the avatar size and associated URL.
    */
    'avatarUrls'?: AvatarUrls;
    /**
    * List of the issue types supported by the project.
    */
    'issuetypes'?: Array<IssueTypeIssueCreateMetadata>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "expand",
            "baseName": "expand",
            "type": "string"
        },
        {
            "name": "self",
            "baseName": "self",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "avatarUrls",
            "baseName": "avatarUrls",
            "type": "AvatarUrls"
        },
        {
            "name": "issuetypes",
            "baseName": "issuetypes",
            "type": "Array<IssueTypeIssueCreateMetadata>"
        }    ];

    static getAttributeTypeMap() {
        return ProjectIssueCreateMetadata.attributeTypeMap;
    }
}

