/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AvatarUrls } from './avatarUrls';
import { UpdatedProjectCategory } from './updatedProjectCategory';

/**
* Details about a next-gen project.
*/
export class ProjectForScope {
    /**
    * The URL of the project details.
    */
    'self'?: string;
    /**
    * The ID of the project.
    */
    'id'?: string;
    /**
    * The key of the project.
    */
    'key'?: string;
    /**
    * The name of the project.
    */
    'name'?: string;
    /**
    * The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes) of the project.
    */
    'projectTypeKey'?: ProjectForScope.ProjectTypeKeyEnum;
    /**
    * The URLs of the project's avatars.
    */
    'avatarUrls'?: AvatarUrls;
    /**
    * The category the project belongs to.
    */
    'projectCategory'?: UpdatedProjectCategory;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "self",
            "baseName": "self",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "projectTypeKey",
            "baseName": "projectTypeKey",
            "type": "ProjectForScope.ProjectTypeKeyEnum"
        },
        {
            "name": "avatarUrls",
            "baseName": "avatarUrls",
            "type": "AvatarUrls"
        },
        {
            "name": "projectCategory",
            "baseName": "projectCategory",
            "type": "UpdatedProjectCategory"
        }    ];

    static getAttributeTypeMap() {
        return ProjectForScope.attributeTypeMap;
    }
}

export namespace ProjectForScope {
    export enum ProjectTypeKeyEnum {
        Ops = <any> 'ops',
        Software = <any> 'software',
        ServiceDesk = <any> 'service_desk',
        Business = <any> 'business'
    }
}
