/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Avatar } from './avatar';

/**
* List of project avatars.
*/
export class ProjectAvatars {
    /**
    * List of avatars included with Jira. These avatars cannot be deleted.
    */
    'system'?: Array<Avatar>;
    /**
    * List of avatars added to Jira. These avatars may be deleted.
    */
    'custom'?: Array<Avatar>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "system",
            "baseName": "system",
            "type": "Array<Avatar>"
        },
        {
            "name": "custom",
            "baseName": "custom",
            "type": "Array<Avatar>"
        }    ];

    static getAttributeTypeMap() {
        return ProjectAvatars.attributeTypeMap;
    }
}

