/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Application } from './application';
import { RemoteObject } from './remoteObject';

/**
* Details of a remote issue link.
*/
export class RemoteIssueLinkRequest {
    /**
    * The global ID of the link, such as the ID of the item on the remote system. The maximum length is 255 characters.
    */
    'globalId'?: string;
    'application'?: Application;
    /**
    * Description of the relationship between the issue and the linked item.
    */
    'relationship'?: string;
    'object': RemoteObject;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "globalId",
            "baseName": "globalId",
            "type": "string"
        },
        {
            "name": "application",
            "baseName": "application",
            "type": "Application"
        },
        {
            "name": "relationship",
            "baseName": "relationship",
            "type": "string"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "RemoteObject"
        }    ];

    static getAttributeTypeMap() {
        return RemoteIssueLinkRequest.attributeTypeMap;
    }
}

