/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Icon } from './icon';
import { Status } from './status';

/**
* The linked item.
*/
export class RemoteObject {
    /**
    * The URL of the item.
    */
    'url': string;
    /**
    * The title of the item.
    */
    'title': string;
    /**
    * The summary details of the item.
    */
    'summary'?: string;
    'icon'?: Icon;
    'status'?: Status;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string"
        },
        {
            "name": "icon",
            "baseName": "icon",
            "type": "Icon"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "Status"
        }    ];

    static getAttributeTypeMap() {
        return RemoteObject.attributeTypeMap;
    }
}

