/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SimpleErrorCollection } from './simpleErrorCollection';

/**
* Details about the removal and replacement of an issue field option.
*/
export class RemoveOptionFromIssues {
    /**
    * The IDs of the modified issues.
    */
    'modifiedIssues'?: Array<number>;
    /**
    * The IDs of the unchanged issues, due to errors preventing modification.
    */
    'unmodifiedIssues'?: Array<number>;
    /**
    * A collection of errors related to unchanged issues. The collection size is limited, which means not all errors may be returned.
    */
    'errors'?: SimpleErrorCollection;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "modifiedIssues",
            "baseName": "modifiedIssues",
            "type": "Array<number>"
        },
        {
            "name": "unmodifiedIssues",
            "baseName": "unmodifiedIssues",
            "type": "Array<number>"
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "SimpleErrorCollection"
        }    ];

    static getAttributeTypeMap() {
        return RemoveOptionFromIssues.attributeTypeMap;
    }
}

