/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Details about a remote link.
*/
export class RemoteLinkDetails {
    /**
    * The URL of the remote link details.
    */
    'self'?: string;
    /**
    * The name of the remote link.
    */
    'name'?: string;
    /**
    * The URL of the remote link.
    */
    'link'?: any;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "self",
            "baseName": "self",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return RemoteLinkDetails.attributeTypeMap;
    }
}

