/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Details of the permission.
*/
export class RestrictedPermission {
    /**
    * The ID of the permission. Either `id` or `key` must be specified. Use [Get all permissions](#api-api-3-permissions-get) to get the list of permissions.
    */
    'id'?: string;
    /**
    * The key of the permission. Either `id` or `key` must be specified. Use [Get all permissions](#api-api-3-permissions-get) to get the list of permissions.
    */
    'key'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RestrictedPermission.attributeTypeMap;
    }
}

