/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProjectRoleGroupBean } from './projectRoleGroupBean';
import { ProjectRoleUserBean } from './projectRoleUserBean';

/**
* Details about a user assigned to a project role.
*/
export class RoleActor {
    'id'?: number;
    /**
    * The display name of the user. Depending on the user’s privacy setting, this may return an alternative value.
    */
    'displayName'?: string;
    'type'?: string;
    /**
    * This property has been deprecated in favour of `accountId` due to privacy changes. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.   The username of the user.
    */
    'name'?: string;
    'avatarUrl'?: string;
    'actorUser'?: ProjectRoleUserBean;
    'actorGroup'?: ProjectRoleGroupBean;
    'user'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "avatarUrl",
            "baseName": "avatarUrl",
            "type": "string"
        },
        {
            "name": "actorUser",
            "baseName": "actorUser",
            "type": "ProjectRoleUserBean"
        },
        {
            "name": "actorGroup",
            "baseName": "actorGroup",
            "type": "ProjectRoleGroupBean"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RoleActor.attributeTypeMap;
    }
}

