/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApplicationRole } from './applicationRole';

export class SimpleListWrapperApplicationRole {
    'size'?: number;
    'maxResults'?: number;
    'items'?: Array<ApplicationRole>;
    'pagingCallback'?: any;
    'callback'?: any;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "size",
            "baseName": "size",
            "type": "number"
        },
        {
            "name": "maxResults",
            "baseName": "max-results",
            "type": "number"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<ApplicationRole>"
        },
        {
            "name": "pagingCallback",
            "baseName": "pagingCallback",
            "type": "any"
        },
        {
            "name": "callback",
            "baseName": "callback",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return SimpleListWrapperApplicationRole.attributeTypeMap;
    }
}

