/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Icon } from './icon';

/**
* The status of the item.
*/
export class Status {
    /**
    * Indicates whether the item is resolved.
    */
    'resolved'?: boolean;
    'icon'?: Icon;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "resolved",
            "baseName": "resolved",
            "type": "boolean"
        },
        {
            "name": "icon",
            "baseName": "icon",
            "type": "Icon"
        }    ];

    static getAttributeTypeMap() {
        return Status.attributeTypeMap;
    }
}

