/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Avatar } from './avatar';

/**
* List of system avatars.
*/
export class SystemAvatars {
    /**
    * A list of avatar details.
    */
    'system'?: Array<Avatar>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "system",
            "baseName": "system",
            "type": "Array<Avatar>"
        }    ];

    static getAttributeTypeMap() {
        return SystemAvatars.attributeTypeMap;
    }
}

