/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AvatarUrls } from './avatarUrls';

/**
* User details. Note, cannot be specified as a body parameter in [Add worklog](#api-api-3-issue-issue-issueIdOrKey-worklog-post) or [Update worklog](#api-api-3-issue-issueIdOrKey-worklog-id-put).
*/
export class UserDetails {
    /**
    * The URL of the user.
    */
    'self'?: string;
    /**
    * This property has been deprecated in favour of `accountId` due to privacy changes. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.   The username of the user.
    */
    'name'?: string;
    /**
    * This property has been deprecated in favour of `accountId` due to privacy changes. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.   The key of the user.
    */
    'key'?: string;
    /**
    * The accountId of the user, which uniquely identifies the user across all Atlassian products. For example, _384093:32b4d9w0-f6a5-3535-11a3-9c8c88d10192_.
    */
    'accountId'?: string;
    /**
    * The email address of the user. Depending on the user’s privacy setting, this may be returned as null.
    */
    'emailAddress'?: string;
    /**
    * The avatars of the user.
    */
    'avatarUrls'?: AvatarUrls;
    /**
    * The display name of the user. Depending on the user’s privacy setting, this may return an alternative value.
    */
    'displayName'?: string;
    /**
    * Whether the user is active.
    */
    'active'?: boolean;
    /**
    * The time zone specified in the user's profile. Depending on the user’s privacy setting, this may be returned as null.
    */
    'timeZone'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "self",
            "baseName": "self",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string"
        },
        {
            "name": "emailAddress",
            "baseName": "emailAddress",
            "type": "string"
        },
        {
            "name": "avatarUrls",
            "baseName": "avatarUrls",
            "type": "AvatarUrls"
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string"
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean"
        },
        {
            "name": "timeZone",
            "baseName": "timeZone",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UserDetails.attributeTypeMap;
    }
}

