/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Counts of the number of issues in various statuses.
*/
export class VersionIssuesStatus {
    /**
    * Count of issues with a status other than _to do_, _in progress_, and _done_.
    */
    'unmapped'?: number;
    /**
    * Count of issues with status _to do_.
    */
    'toDo'?: number;
    /**
    * Count of issues with status _in progress_.
    */
    'inProgress'?: number;
    /**
    * Count of issues with status _done_.
    */
    'done'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "unmapped",
            "baseName": "unmapped",
            "type": "number"
        },
        {
            "name": "toDo",
            "baseName": "toDo",
            "type": "number"
        },
        {
            "name": "inProgress",
            "baseName": "inProgress",
            "type": "number"
        },
        {
            "name": "done",
            "baseName": "done",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return VersionIssuesStatus.attributeTypeMap;
    }
}

