/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { User } from './user';

/**
* The details of votes on an issue.
*/
export class Votes {
    /**
    * The URL of these issue vote details.
    */
    'self'?: string;
    /**
    * The number of votes on the issue.
    */
    'votes'?: number;
    /**
    * Indicates whether the user making this request has voted on the issue.
    */
    'hasVoted'?: boolean;
    /**
    * List of the users who have voted on this issue. An empty list is returned when the calling user doesn't have the _View voters and watchers_ project permission.
    */
    'voters'?: Array<User>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "self",
            "baseName": "self",
            "type": "string"
        },
        {
            "name": "votes",
            "baseName": "votes",
            "type": "number"
        },
        {
            "name": "hasVoted",
            "baseName": "hasVoted",
            "type": "boolean"
        },
        {
            "name": "voters",
            "baseName": "voters",
            "type": "Array<User>"
        }    ];

    static getAttributeTypeMap() {
        return Votes.attributeTypeMap;
    }
}

