/**
 * Jira Cloud REST API
 * Jira Cloud REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Details about a workflow.
*/
export class Workflow {
    /**
    * The name of the workflow.
    */
    'name'?: string;
    /**
    * The description of the workflow.
    */
    'description'?: string;
    /**
    * The datetime the workflow was last modified.
    */
    'lastModifiedDate'?: string;
    /**
    * The username of the user who last modified the workflow. Note that this property has been deprecated in favor of `lastModifiedUserAccountId` due to privacy changes. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.
    */
    'lastModifiedUser'?: string;
    /**
    * The account ID of the user and last modified the workflow.
    */
    'lastModifiedUserAccountId'?: string;
    /**
    * The number of steps included in the workflow.
    */
    'steps'?: number;
    '_default'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "lastModifiedDate",
            "baseName": "lastModifiedDate",
            "type": "string"
        },
        {
            "name": "lastModifiedUser",
            "baseName": "lastModifiedUser",
            "type": "string"
        },
        {
            "name": "lastModifiedUserAccountId",
            "baseName": "lastModifiedUserAccountId",
            "type": "string"
        },
        {
            "name": "steps",
            "baseName": "steps",
            "type": "number"
        },
        {
            "name": "_default",
            "baseName": "default",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Workflow.attributeTypeMap;
    }
}

